### ISSUE TITLE
Had to target specific versions of ethcore dependencies to compile

### ISSUE THREAD

**Issue by apmilen** [dapphub/ethrun#2]
needed this to compile:
```
cargo update -p hyper:0.9.4 --precise 6baea9d444dd1652220ee9b4aeadaebb3de6a955
cargo update -p rotor --precise c1a2dd0046c5ea2517a5b637fca8ee2e77021e82
```

perhaps we can specify these in `Cargo.toml` or `Cargo.lock` ?

**Comment by mbrock** [comment]
Nice work, I bet that was pretty annoying to figure out... Chasing dependency errors in the ethcore/Rust jungle is kind of nightmarish. The latest ethcore depends on hardware wallet code that requires `libudev-dev` to build, etc etc. I'll commit the new lock file and also put a binary on the releases page.
